#pragma once

#include "reflex.h"

#define NOINLINE REFLEX_NOINLINE

#define SELF (*this)

#define ASSERT(X) REFLEX_ASSERT(X)
#define USING(X) REFLEX_USE(X)

#define CREATE(TYPE, ...) REFLEX_CREATE(TYPE, __VA_ARGS__)

#define LOOP_PTR(START, VAR, N) REFLEX_LOOP_PTR(START, VAR, N)
#define RLOOP_PTR(START, VAR, N) REFLEX_RLOOP_PTR(START, VAR, N)
#define LOOP(VAR, N) REFLEX_LOOP(VAR, N)
#define RLOOP(VAR, N) REFLEX_RLOOP(VAR, N)

#define FOREACH(I,CONTAINER) REFLEX_FOREACH(I,CONTAINER)
#define RFOREACH(I,CONTAINER) REFLEX_RFOREACH(I,CONTAINER)

USING(Reflex);
