@ECHO off
SETLOCAL

SET "SCRIPT_DIR=%~dp0"
FOR %%I IN ("_REFLEX-PATH_") DO SET "REFLEX_ROOT=%%~fI"
SET "TARGET_DIR=%SCRIPT_DIR%agents\reflex\"

IF EXIST "%TARGET_DIR%" RMDIR /S /Q "%TARGET_DIR%"

MKDIR "%TARGET_DIR%" >NUL

REM XCOPY "%REFLEX_ROOT%\include" "%TARGET_DIR%\include\" /E /I /Y >NUL
REM IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%

XCOPY "%REFLEX_ROOT%\agents" "%TARGET_DIR%" /E /I /Y >NUL
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%

ECHO Reflex reference files updated.

ENDLOCAL
EXIT /B 0
