#pragma once

#include "../types.h"




//
//Detail

namespace Reflex::Detail
{

	template <class BINDER> const typename BINDER::Type & TBind(UInt8 flags);

	template <class BINDER> const typename BINDER::Type * TBind();

}




//
//tbinder macros

#define REFLEX_TBINDER_1P(FN_NAME) struct FN_NAME##Binder { static const Reflex::UInt N = 1; typedef decltype(&FN_NAME<false>) Type; template <bool A> static Type GetFn(){return &FN_NAME<A>;} static Type Bind(Reflex::UInt8 flags){ return REFLEX_TBIND(FN_NAME,flags); }};

#define REFLEX_TBINDER_2P(FN_NAME) struct FN_NAME##Binder { static const Reflex::UInt N = 2; typedef decltype(&FN_NAME<false,false>) Type; template <bool A, bool B> static Type GetFn(){return &FN_NAME<A,B>;} static Type Bind(Reflex::UInt8 flags){ return REFLEX_TBIND(FN_NAME,flags); }};

#define REFLEX_TBINDER_3P(FN_NAME) struct FN_NAME##Binder { static const Reflex::UInt N = 3; typedef decltype(&FN_NAME<false,false,false>) Type; template <bool A, bool B, bool C> static Type GetFn(){return &FN_NAME<A,B,C>;} static Type Bind(Reflex::UInt8 flags){ return REFLEX_TBIND(FN_NAME,flags); }};

#define REFLEX_TBINDER_4P(FN_NAME) struct FN_NAME##Binder { static const Reflex::UInt N = 4; typedef decltype(&FN_NAME<false,false,false,false>) Type; template <bool A, bool B, bool C, bool D> static Type GetFn(){return &FN_NAME<A,B,C,D>;} static Type Bind(Reflex::UInt8 flags){ return REFLEX_TBIND(FN_NAME,flags); }};

#define REFLEX_TBINDER_5P(FN_NAME) struct FN_NAME##Binder { static const Reflex::UInt N = 5; typedef decltype(&FN_NAME<false,false,false,false,false>) Type; template <bool A, bool B, bool C, bool D, bool E> static Type GetFn(){return &FN_NAME<A,B,C,D,E>;} static Type Bind(Reflex::UInt8 flags){ return REFLEX_TBIND(FN_NAME,flags); }};

#define REFLEX_TBINDER_6P(FN_NAME) struct FN_NAME##Binder { static const Reflex::UInt N = 6; typedef decltype(&FN_NAME<false,false,false,false,false,false>) Type; template <bool A, bool B, bool C, bool D, bool E, bool F> static Type GetFn(){return &FN_NAME<A,B,C,D,E,F>;} static Type Bind(Reflex::UInt8 flags){ return REFLEX_TBIND(FN_NAME,flags); }};

#define REFLEX_TBINDER_7P(FN_NAME) struct FN_NAME##Binder { static const Reflex::UInt N = 7; typedef decltype(&FN_NAME<false,false,false,false,false,false,false>) Type; template <bool A, bool B, bool C, bool D, bool E, bool F, bool G> static Type GetFn(){return &FN_NAME<A,B,C,D,E,F,G>;} static Type Bind(Reflex::UInt8 flags){ return REFLEX_TBIND(FN_NAME,flags); }};

#define REFLEX_TBINDER_8P(FN_NAME) struct FN_NAME##Binder { static const Reflex::UInt N = 8; typedef decltype(&FN_NAME<false,false,false,false,false,false,false,false>) Type; template <bool A, bool B, bool C, bool D, bool E, bool F, bool G, bool H> static Type GetFn(){return &FN_NAME<A,B,C,D,E,F,G,H>;} static Type Bind(Reflex::UInt8 flags){ return REFLEX_TBIND(FN_NAME,flags); }};




//
//impl

#define REFLEX_TBIND(FN_NAME, FLAGS) Reflex::Detail::TBind<FN_NAME##Binder>(FLAGS)

REFLEX_NS(Reflex::Detail)

template <class BINDER, UInt NPARAM> struct TBinder {};

template <class BINDER> struct TBinder <BINDER,1> {static const typename BINDER::Type kFunctions[2];};

template <class BINDER> struct TBinder <BINDER,2> {static const typename BINDER::Type kFunctions[4];};

template <class BINDER> struct TBinder <BINDER,3> {static const typename BINDER::Type kFunctions[8];};

template <class BINDER> struct TBinder <BINDER,4> {static const typename BINDER::Type kFunctions[16];};

template <class BINDER> struct TBinder <BINDER,5> {static const typename BINDER::Type kFunctions[32];};

template <class BINDER> struct TBinder <BINDER,6> {static const typename BINDER::Type kFunctions[64];};

template <class BINDER> struct TBinder <BINDER,7> {static const typename BINDER::Type kFunctions[128];};

template <class BINDER> struct TBinder <BINDER,8> {static const typename BINDER::Type kFunctions[256];};

REFLEX_END

template <class BINDER> REFLEX_INLINE const typename BINDER::Type & Reflex::Detail::TBind(UInt8 flags)
{
	using Binder = Detail::TBinder<BINDER,BINDER::N>;

	return Binder::kFunctions[flags & (sizeof(Binder::kFunctions) / sizeof(typename BINDER::Type) - 1)];
}

template <class BINDER> REFLEX_INLINE const typename BINDER::Type * Reflex::Detail::TBind()
{
	using Binder = Detail::TBinder<BINDER,BINDER::N>;

	return Binder::kFunctions;
}

template <class BINDER> const typename BINDER::Type Reflex::Detail::TBinder<BINDER,1>::kFunctions[2] =
{
	BINDER::template GetFn<false>(),
	BINDER::template GetFn<true>(),
};

template <class BINDER> const typename BINDER::Type Reflex::Detail::TBinder<BINDER,2>::kFunctions[4] =
{
	BINDER::template GetFn<false,false>(),
	BINDER::template GetFn<true,false>(),
	BINDER::template GetFn<false,true>(),
	BINDER::template GetFn<true,true>(),
};

template <class BINDER> const typename BINDER::Type Reflex::Detail::TBinder<BINDER,3>::kFunctions[8] =
{
	BINDER::template GetFn<false,false,false>(),
	BINDER::template GetFn<true,false,false>(),
	BINDER::template GetFn<false,true,false>(),
	BINDER::template GetFn<true,true,false>(),

	BINDER::template GetFn<false,false,true>(),
	BINDER::template GetFn<true,false,true>(),
	BINDER::template GetFn<false,true,true>(),
	BINDER::template GetFn<true,true,true>(),
};

template <class BINDER> const typename BINDER::Type Reflex::Detail::TBinder<BINDER,4>::kFunctions[16] =
{
	BINDER::template GetFn<false,false,false,false>(),
	BINDER::template GetFn<true,false,false,false>(),
	BINDER::template GetFn<false,true,false,false>(),
	BINDER::template GetFn<true,true,false,false>(),
	BINDER::template GetFn<false,false,true,false>(),
	BINDER::template GetFn<true,false,true,false>(),
	BINDER::template GetFn<false,true,true,false>(),
	BINDER::template GetFn<true,true,true,false>(),

	BINDER::template GetFn<false,false,false,true>(),
	BINDER::template GetFn<true,false,false,true>(),
	BINDER::template GetFn<false,true,false,true>(),
	BINDER::template GetFn<true,true,false,true>(),
	BINDER::template GetFn<false,false,true,true>(),
	BINDER::template GetFn<true,false,true,true>(),
	BINDER::template GetFn<false,true,true,true>(),
	BINDER::template GetFn<true,true,true,true>(),
};

template <class BINDER> const typename BINDER::Type Reflex::Detail::TBinder<BINDER,5>::kFunctions[32] =
{
	BINDER::template GetFn<false,false,false,false,false>(),
	BINDER::template GetFn<true,false,false,false,false>(),
	BINDER::template GetFn<false,true,false,false,false>(),
	BINDER::template GetFn<true,true,false,false,false>(),
	BINDER::template GetFn<false,false,true,false,false>(),
	BINDER::template GetFn<true,false,true,false,false>(),
	BINDER::template GetFn<false,true,true,false,false>(),
	BINDER::template GetFn<true,true,true,false,false>(),
	BINDER::template GetFn<false,false,false,true,false>(),
	BINDER::template GetFn<true,false,false,true,false>(),
	BINDER::template GetFn<false,true,false,true,false>(),
	BINDER::template GetFn<true,true,false,true,false>(),
	BINDER::template GetFn<false,false,true,true,false>(),
	BINDER::template GetFn<true,false,true,true,false>(),
	BINDER::template GetFn<false,true,true,true,false>(),
	BINDER::template GetFn<true,true,true,true,false>(),

	BINDER::template GetFn<false,false,false,false,true>(),
	BINDER::template GetFn<true,false,false,false,true>(),
	BINDER::template GetFn<false,true,false,false,true>(),
	BINDER::template GetFn<true,true,false,false,true>(),
	BINDER::template GetFn<false,false,true,false,true>(),
	BINDER::template GetFn<true,false,true,false,true>(),
	BINDER::template GetFn<false,true,true,false,true>(),
	BINDER::template GetFn<true,true,true,false,true>(),
	BINDER::template GetFn<false,false,false,true,true>(),
	BINDER::template GetFn<true,false,false,true,true>(),
	BINDER::template GetFn<false,true,false,true,true>(),
	BINDER::template GetFn<true,true,false,true,true>(),
	BINDER::template GetFn<false,false,true,true,true>(),
	BINDER::template GetFn<true,false,true,true,true>(),
	BINDER::template GetFn<false,true,true,true,true>(),
	BINDER::template GetFn<true,true,true,true,true>(),
};

template <class BINDER> const typename BINDER::Type Reflex::Detail::TBinder<BINDER,6>::kFunctions[64] =
{
	BINDER::template GetFn<false,false,false,false,false,false>(),
	BINDER::template GetFn<true,false,false,false,false,false>(),
	BINDER::template GetFn<false,true,false,false,false,false>(),
	BINDER::template GetFn<true,true,false,false,false,false>(),
	BINDER::template GetFn<false,false,true,false,false,false>(),
	BINDER::template GetFn<true,false,true,false,false,false>(),
	BINDER::template GetFn<false,true,true,false,false,false>(),
	BINDER::template GetFn<true,true,true,false,false,false>(),
	BINDER::template GetFn<false,false,false,true,false,false>(),
	BINDER::template GetFn<true,false,false,true,false,false>(),
	BINDER::template GetFn<false,true,false,true,false,false>(),
	BINDER::template GetFn<true,true,false,true,false,false>(),
	BINDER::template GetFn<false,false,true,true,false,false>(),
	BINDER::template GetFn<true,false,true,true,false,false>(),
	BINDER::template GetFn<false,true,true,true,false,false>(),
	BINDER::template GetFn<true,true,true,true,false,false>(),
	BINDER::template GetFn<false,false,false,false,true,false>(),
	BINDER::template GetFn<true,false,false,false,true,false>(),
	BINDER::template GetFn<false,true,false,false,true,false>(),
	BINDER::template GetFn<true,true,false,false,true,false>(),
	BINDER::template GetFn<false,false,true,false,true,false>(),
	BINDER::template GetFn<true,false,true,false,true,false>(),
	BINDER::template GetFn<false,true,true,false,true,false>(),
	BINDER::template GetFn<true,true,true,false,true,false>(),
	BINDER::template GetFn<false,false,false,true,true,false>(),
	BINDER::template GetFn<true,false,false,true,true,false>(),
	BINDER::template GetFn<false,true,false,true,true,false>(),
	BINDER::template GetFn<true,true,false,true,true,false>(),
	BINDER::template GetFn<false,false,true,true,true,false>(),
	BINDER::template GetFn<true,false,true,true,true,false>(),
	BINDER::template GetFn<false,true,true,true,true,false>(),
	BINDER::template GetFn<true,true,true,true,true,false>(),

	BINDER::template GetFn<false,false,false,false,false,true>(),
	BINDER::template GetFn<true,false,false,false,false,true>(),
	BINDER::template GetFn<false,true,false,false,false,true>(),
	BINDER::template GetFn<true,true,false,false,false,true>(),
	BINDER::template GetFn<false,false,true,false,false,true>(),
	BINDER::template GetFn<true,false,true,false,false,true>(),
	BINDER::template GetFn<false,true,true,false,false,true>(),
	BINDER::template GetFn<true,true,true,false,false,true>(),
	BINDER::template GetFn<false,false,false,true,false,true>(),
	BINDER::template GetFn<true,false,false,true,false,true>(),
	BINDER::template GetFn<false,true,false,true,false,true>(),
	BINDER::template GetFn<true,true,false,true,false,true>(),
	BINDER::template GetFn<false,false,true,true,false,true>(),
	BINDER::template GetFn<true,false,true,true,false,true>(),
	BINDER::template GetFn<false,true,true,true,false,true>(),
	BINDER::template GetFn<true,true,true,true,false,true>(),
	BINDER::template GetFn<false,false,false,false,true,true>(),
	BINDER::template GetFn<true,false,false,false,true,true>(),
	BINDER::template GetFn<false,true,false,false,true,true>(),
	BINDER::template GetFn<true,true,false,false,true,true>(),
	BINDER::template GetFn<false,false,true,false,true,true>(),
	BINDER::template GetFn<true,false,true,false,true,true>(),
	BINDER::template GetFn<false,true,true,false,true,true>(),
	BINDER::template GetFn<true,true,true,false,true,true>(),
	BINDER::template GetFn<false,false,false,true,true,true>(),
	BINDER::template GetFn<true,false,false,true,true,true>(),
	BINDER::template GetFn<false,true,false,true,true,true>(),
	BINDER::template GetFn<true,true,false,true,true,true>(),
	BINDER::template GetFn<false,false,true,true,true,true>(),
	BINDER::template GetFn<true,false,true,true,true,true>(),
	BINDER::template GetFn<false,true,true,true,true,true>(),
	BINDER::template GetFn<true,true,true,true,true,true>(),
};

template <class BINDER> const typename BINDER::Type Reflex::Detail::TBinder<BINDER,7>::kFunctions[128] =
{
	BINDER::template GetFn<false,false,false,false,false,false,false>(),
	BINDER::template GetFn<true,false,false,false,false,false,false>(),
	BINDER::template GetFn<false,true,false,false,false,false,false>(),
	BINDER::template GetFn<true,true,false,false,false,false,false>(),
	BINDER::template GetFn<false,false,true,false,false,false,false>(),
	BINDER::template GetFn<true,false,true,false,false,false,false>(),
	BINDER::template GetFn<false,true,true,false,false,false,false>(),
	BINDER::template GetFn<true,true,true,false,false,false,false>(),
	BINDER::template GetFn<false,false,false,true,false,false,false>(),
	BINDER::template GetFn<true,false,false,true,false,false,false>(),
	BINDER::template GetFn<false,true,false,true,false,false,false>(),
	BINDER::template GetFn<true,true,false,true,false,false,false>(),
	BINDER::template GetFn<false,false,true,true,false,false,false>(),
	BINDER::template GetFn<true,false,true,true,false,false,false>(),
	BINDER::template GetFn<false,true,true,true,false,false,false>(),
	BINDER::template GetFn<true,true,true,true,false,false,false>(),
	BINDER::template GetFn<false,false,false,false,true,false,false>(),
	BINDER::template GetFn<true,false,false,false,true,false,false>(),
	BINDER::template GetFn<false,true,false,false,true,false,false>(),
	BINDER::template GetFn<true,true,false,false,true,false,false>(),
	BINDER::template GetFn<false,false,true,false,true,false,false>(),
	BINDER::template GetFn<true,false,true,false,true,false,false>(),
	BINDER::template GetFn<false,true,true,false,true,false,false>(),
	BINDER::template GetFn<true,true,true,false,true,false,false>(),
	BINDER::template GetFn<false,false,false,true,true,false,false>(),
	BINDER::template GetFn<true,false,false,true,true,false,false>(),
	BINDER::template GetFn<false,true,false,true,true,false,false>(),
	BINDER::template GetFn<true,true,false,true,true,false,false>(),
	BINDER::template GetFn<false,false,true,true,true,false,false>(),
	BINDER::template GetFn<true,false,true,true,true,false,false>(),
	BINDER::template GetFn<false,true,true,true,true,false,false>(),
	BINDER::template GetFn<true,true,true,true,true,false,false>(),
	BINDER::template GetFn<false,false,false,false,false,true,false>(),
	BINDER::template GetFn<true,false,false,false,false,true,false>(),
	BINDER::template GetFn<false,true,false,false,false,true,false>(),
	BINDER::template GetFn<true,true,false,false,false,true,false>(),
	BINDER::template GetFn<false,false,true,false,false,true,false>(),
	BINDER::template GetFn<true,false,true,false,false,true,false>(),
	BINDER::template GetFn<false,true,true,false,false,true,false>(),
	BINDER::template GetFn<true,true,true,false,false,true,false>(),
	BINDER::template GetFn<false,false,false,true,false,true,false>(),
	BINDER::template GetFn<true,false,false,true,false,true,false>(),
	BINDER::template GetFn<false,true,false,true,false,true,false>(),
	BINDER::template GetFn<true,true,false,true,false,true,false>(),
	BINDER::template GetFn<false,false,true,true,false,true,false>(),
	BINDER::template GetFn<true,false,true,true,false,true,false>(),
	BINDER::template GetFn<false,true,true,true,false,true,false>(),
	BINDER::template GetFn<true,true,true,true,false,true,false>(),
	BINDER::template GetFn<false,false,false,false,true,true,false>(),
	BINDER::template GetFn<true,false,false,false,true,true,false>(),
	BINDER::template GetFn<false,true,false,false,true,true,false>(),
	BINDER::template GetFn<true,true,false,false,true,true,false>(),
	BINDER::template GetFn<false,false,true,false,true,true,false>(),
	BINDER::template GetFn<true,false,true,false,true,true,false>(),
	BINDER::template GetFn<false,true,true,false,true,true,false>(),
	BINDER::template GetFn<true,true,true,false,true,true,false>(),
	BINDER::template GetFn<false,false,false,true,true,true,false>(),
	BINDER::template GetFn<true,false,false,true,true,true,false>(),
	BINDER::template GetFn<false,true,false,true,true,true,false>(),
	BINDER::template GetFn<true,true,false,true,true,true,false>(),
	BINDER::template GetFn<false,false,true,true,true,true,false>(),
	BINDER::template GetFn<true,false,true,true,true,true,false>(),
	BINDER::template GetFn<false,true,true,true,true,true,false>(),
	BINDER::template GetFn<true,true,true,true,true,true,false>(),

	BINDER::template GetFn<false,false,false,false,false,false,true>(),
	BINDER::template GetFn<true,false,false,false,false,false,true>(),
	BINDER::template GetFn<false,true,false,false,false,false,true>(),
	BINDER::template GetFn<true,true,false,false,false,false,true>(),
	BINDER::template GetFn<false,false,true,false,false,false,true>(),
	BINDER::template GetFn<true,false,true,false,false,false,true>(),
	BINDER::template GetFn<false,true,true,false,false,false,true>(),
	BINDER::template GetFn<true,true,true,false,false,false,true>(),
	BINDER::template GetFn<false,false,false,true,false,false,true>(),
	BINDER::template GetFn<true,false,false,true,false,false,true>(),
	BINDER::template GetFn<false,true,false,true,false,false,true>(),
	BINDER::template GetFn<true,true,false,true,false,false,true>(),
	BINDER::template GetFn<false,false,true,true,false,false,true>(),
	BINDER::template GetFn<true,false,true,true,false,false,true>(),
	BINDER::template GetFn<false,true,true,true,false,false,true>(),
	BINDER::template GetFn<true,true,true,true,false,false,true>(),
	BINDER::template GetFn<false,false,false,false,true,false,true>(),
	BINDER::template GetFn<true,false,false,false,true,false,true>(),
	BINDER::template GetFn<false,true,false,false,true,false,true>(),
	BINDER::template GetFn<true,true,false,false,true,false,true>(),
	BINDER::template GetFn<false,false,true,false,true,false,true>(),
	BINDER::template GetFn<true,false,true,false,true,false,true>(),
	BINDER::template GetFn<false,true,true,false,true,false,true>(),
	BINDER::template GetFn<true,true,true,false,true,false,true>(),
	BINDER::template GetFn<false,false,false,true,true,false,true>(),
	BINDER::template GetFn<true,false,false,true,true,false,true>(),
	BINDER::template GetFn<false,true,false,true,true,false,true>(),
	BINDER::template GetFn<true,true,false,true,true,false,true>(),
	BINDER::template GetFn<false,false,true,true,true,false,true>(),
	BINDER::template GetFn<true,false,true,true,true,false,true>(),
	BINDER::template GetFn<false,true,true,true,true,false,true>(),
	BINDER::template GetFn<true,true,true,true,true,false,true>(),
	BINDER::template GetFn<false,false,false,false,false,true,true>(),
	BINDER::template GetFn<true,false,false,false,false,true,true>(),
	BINDER::template GetFn<false,true,false,false,false,true,true>(),
	BINDER::template GetFn<true,true,false,false,false,true,true>(),
	BINDER::template GetFn<false,false,true,false,false,true,true>(),
	BINDER::template GetFn<true,false,true,false,false,true,true>(),
	BINDER::template GetFn<false,true,true,false,false,true,true>(),
	BINDER::template GetFn<true,true,true,false,false,true,true>(),
	BINDER::template GetFn<false,false,false,true,false,true,true>(),
	BINDER::template GetFn<true,false,false,true,false,true,true>(),
	BINDER::template GetFn<false,true,false,true,false,true,true>(),
	BINDER::template GetFn<true,true,false,true,false,true,true>(),
	BINDER::template GetFn<false,false,true,true,false,true,true>(),
	BINDER::template GetFn<true,false,true,true,false,true,true>(),
	BINDER::template GetFn<false,true,true,true,false,true,true>(),
	BINDER::template GetFn<true,true,true,true,false,true,true>(),
	BINDER::template GetFn<false,false,false,false,true,true,true>(),
	BINDER::template GetFn<true,false,false,false,true,true,true>(),
	BINDER::template GetFn<false,true,false,false,true,true,true>(),
	BINDER::template GetFn<true,true,false,false,true,true,true>(),
	BINDER::template GetFn<false,false,true,false,true,true,true>(),
	BINDER::template GetFn<true,false,true,false,true,true,true>(),
	BINDER::template GetFn<false,true,true,false,true,true,true>(),
	BINDER::template GetFn<true,true,true,false,true,true,true>(),
	BINDER::template GetFn<false,false,false,true,true,true,true>(),
	BINDER::template GetFn<true,false,false,true,true,true,true>(),
	BINDER::template GetFn<false,true,false,true,true,true,true>(),
	BINDER::template GetFn<true,true,false,true,true,true,true>(),
	BINDER::template GetFn<false,false,true,true,true,true,true>(),
	BINDER::template GetFn<true,false,true,true,true,true,true>(),
	BINDER::template GetFn<false,true,true,true,true,true,true>(),
	BINDER::template GetFn<true,true,true,true,true,true,true>(),
};

template <class BINDER> const typename BINDER::Type Reflex::Detail::TBinder<BINDER,8>::kFunctions[256] =
{
	BINDER::template GetFn<false,false,false,false,false,false,false,false>(),
	BINDER::template GetFn<true,false,false,false,false,false,false,false>(),
	BINDER::template GetFn<false,true,false,false,false,false,false,false>(),
	BINDER::template GetFn<true,true,false,false,false,false,false,false>(),
	BINDER::template GetFn<false,false,true,false,false,false,false,false>(),
	BINDER::template GetFn<true,false,true,false,false,false,false,false>(),
	BINDER::template GetFn<false,true,true,false,false,false,false,false>(),
	BINDER::template GetFn<true,true,true,false,false,false,false,false>(),
	BINDER::template GetFn<false,false,false,true,false,false,false,false>(),
	BINDER::template GetFn<true,false,false,true,false,false,false,false>(),
	BINDER::template GetFn<false,true,false,true,false,false,false,false>(),
	BINDER::template GetFn<true,true,false,true,false,false,false,false>(),
	BINDER::template GetFn<false,false,true,true,false,false,false,false>(),
	BINDER::template GetFn<true,false,true,true,false,false,false,false>(),
	BINDER::template GetFn<false,true,true,true,false,false,false,false>(),
	BINDER::template GetFn<true,true,true,true,false,false,false,false>(),
	BINDER::template GetFn<false,false,false,false,true,false,false,false>(),
	BINDER::template GetFn<true,false,false,false,true,false,false,false>(),
	BINDER::template GetFn<false,true,false,false,true,false,false,false>(),
	BINDER::template GetFn<true,true,false,false,true,false,false,false>(),
	BINDER::template GetFn<false,false,true,false,true,false,false,false>(),
	BINDER::template GetFn<true,false,true,false,true,false,false,false>(),
	BINDER::template GetFn<false,true,true,false,true,false,false,false>(),
	BINDER::template GetFn<true,true,true,false,true,false,false,false>(),
	BINDER::template GetFn<false,false,false,true,true,false,false,false>(),
	BINDER::template GetFn<true,false,false,true,true,false,false,false>(),
	BINDER::template GetFn<false,true,false,true,true,false,false,false>(),
	BINDER::template GetFn<true,true,false,true,true,false,false,false>(),
	BINDER::template GetFn<false,false,true,true,true,false,false,false>(),
	BINDER::template GetFn<true,false,true,true,true,false,false,false>(),
	BINDER::template GetFn<false,true,true,true,true,false,false,false>(),
	BINDER::template GetFn<true,true,true,true,true,false,false,false>(),
	BINDER::template GetFn<false,false,false,false,false,true,false,false>(),
	BINDER::template GetFn<true,false,false,false,false,true,false,false>(),
	BINDER::template GetFn<false,true,false,false,false,true,false,false>(),
	BINDER::template GetFn<true,true,false,false,false,true,false,false>(),
	BINDER::template GetFn<false,false,true,false,false,true,false,false>(),
	BINDER::template GetFn<true,false,true,false,false,true,false,false>(),
	BINDER::template GetFn<false,true,true,false,false,true,false,false>(),
	BINDER::template GetFn<true,true,true,false,false,true,false,false>(),
	BINDER::template GetFn<false,false,false,true,false,true,false,false>(),
	BINDER::template GetFn<true,false,false,true,false,true,false,false>(),
	BINDER::template GetFn<false,true,false,true,false,true,false,false>(),
	BINDER::template GetFn<true,true,false,true,false,true,false,false>(),
	BINDER::template GetFn<false,false,true,true,false,true,false,false>(),
	BINDER::template GetFn<true,false,true,true,false,true,false,false>(),
	BINDER::template GetFn<false,true,true,true,false,true,false,false>(),
	BINDER::template GetFn<true,true,true,true,false,true,false,false>(),
	BINDER::template GetFn<false,false,false,false,true,true,false,false>(),
	BINDER::template GetFn<true,false,false,false,true,true,false,false>(),
	BINDER::template GetFn<false,true,false,false,true,true,false,false>(),
	BINDER::template GetFn<true,true,false,false,true,true,false,false>(),
	BINDER::template GetFn<false,false,true,false,true,true,false,false>(),
	BINDER::template GetFn<true,false,true,false,true,true,false,false>(),
	BINDER::template GetFn<false,true,true,false,true,true,false,false>(),
	BINDER::template GetFn<true,true,true,false,true,true,false,false>(),
	BINDER::template GetFn<false,false,false,true,true,true,false,false>(),
	BINDER::template GetFn<true,false,false,true,true,true,false,false>(),
	BINDER::template GetFn<false,true,false,true,true,true,false,false>(),
	BINDER::template GetFn<true,true,false,true,true,true,false,false>(),
	BINDER::template GetFn<false,false,true,true,true,true,false,false>(),
	BINDER::template GetFn<true,false,true,true,true,true,false,false>(),
	BINDER::template GetFn<false,true,true,true,true,true,false,false>(),
	BINDER::template GetFn<true,true,true,true,true,true,false,false>(),
	BINDER::template GetFn<false,false,false,false,false,false,true,false>(),
	BINDER::template GetFn<true,false,false,false,false,false,true,false>(),
	BINDER::template GetFn<false,true,false,false,false,false,true,false>(),
	BINDER::template GetFn<true,true,false,false,false,false,true,false>(),
	BINDER::template GetFn<false,false,true,false,false,false,true,false>(),
	BINDER::template GetFn<true,false,true,false,false,false,true,false>(),
	BINDER::template GetFn<false,true,true,false,false,false,true,false>(),
	BINDER::template GetFn<true,true,true,false,false,false,true,false>(),
	BINDER::template GetFn<false,false,false,true,false,false,true,false>(),
	BINDER::template GetFn<true,false,false,true,false,false,true,false>(),
	BINDER::template GetFn<false,true,false,true,false,false,true,false>(),
	BINDER::template GetFn<true,true,false,true,false,false,true,false>(),
	BINDER::template GetFn<false,false,true,true,false,false,true,false>(),
	BINDER::template GetFn<true,false,true,true,false,false,true,false>(),
	BINDER::template GetFn<false,true,true,true,false,false,true,false>(),
	BINDER::template GetFn<true,true,true,true,false,false,true,false>(),
	BINDER::template GetFn<false,false,false,false,true,false,true,false>(),
	BINDER::template GetFn<true,false,false,false,true,false,true,false>(),
	BINDER::template GetFn<false,true,false,false,true,false,true,false>(),
	BINDER::template GetFn<true,true,false,false,true,false,true,false>(),
	BINDER::template GetFn<false,false,true,false,true,false,true,false>(),
	BINDER::template GetFn<true,false,true,false,true,false,true,false>(),
	BINDER::template GetFn<false,true,true,false,true,false,true,false>(),
	BINDER::template GetFn<true,true,true,false,true,false,true,false>(),
	BINDER::template GetFn<false,false,false,true,true,false,true,false>(),
	BINDER::template GetFn<true,false,false,true,true,false,true,false>(),
	BINDER::template GetFn<false,true,false,true,true,false,true,false>(),
	BINDER::template GetFn<true,true,false,true,true,false,true,false>(),
	BINDER::template GetFn<false,false,true,true,true,false,true,false>(),
	BINDER::template GetFn<true,false,true,true,true,false,true,false>(),
	BINDER::template GetFn<false,true,true,true,true,false,true,false>(),
	BINDER::template GetFn<true,true,true,true,true,false,true,false>(),
	BINDER::template GetFn<false,false,false,false,false,true,true,false>(),
	BINDER::template GetFn<true,false,false,false,false,true,true,false>(),
	BINDER::template GetFn<false,true,false,false,false,true,true,false>(),
	BINDER::template GetFn<true,true,false,false,false,true,true,false>(),
	BINDER::template GetFn<false,false,true,false,false,true,true,false>(),
	BINDER::template GetFn<true,false,true,false,false,true,true,false>(),
	BINDER::template GetFn<false,true,true,false,false,true,true,false>(),
	BINDER::template GetFn<true,true,true,false,false,true,true,false>(),
	BINDER::template GetFn<false,false,false,true,false,true,true,false>(),
	BINDER::template GetFn<true,false,false,true,false,true,true,false>(),
	BINDER::template GetFn<false,true,false,true,false,true,true,false>(),
	BINDER::template GetFn<true,true,false,true,false,true,true,false>(),
	BINDER::template GetFn<false,false,true,true,false,true,true,false>(),
	BINDER::template GetFn<true,false,true,true,false,true,true,false>(),
	BINDER::template GetFn<false,true,true,true,false,true,true,false>(),
	BINDER::template GetFn<true,true,true,true,false,true,true,false>(),
	BINDER::template GetFn<false,false,false,false,true,true,true,false>(),
	BINDER::template GetFn<true,false,false,false,true,true,true,false>(),
	BINDER::template GetFn<false,true,false,false,true,true,true,false>(),
	BINDER::template GetFn<true,true,false,false,true,true,true,false>(),
	BINDER::template GetFn<false,false,true,false,true,true,true,false>(),
	BINDER::template GetFn<true,false,true,false,true,true,true,false>(),
	BINDER::template GetFn<false,true,true,false,true,true,true,false>(),
	BINDER::template GetFn<true,true,true,false,true,true,true,false>(),
	BINDER::template GetFn<false,false,false,true,true,true,true,false>(),
	BINDER::template GetFn<true,false,false,true,true,true,true,false>(),
	BINDER::template GetFn<false,true,false,true,true,true,true,false>(),
	BINDER::template GetFn<true,true,false,true,true,true,true,false>(),
	BINDER::template GetFn<false,false,true,true,true,true,true,false>(),
	BINDER::template GetFn<true,false,true,true,true,true,true,false>(),
	BINDER::template GetFn<false,true,true,true,true,true,true,false>(),
	BINDER::template GetFn<true,true,true,true,true,true,true,false>(),

	BINDER::template GetFn<false,false,false,false,false,false,false,true>(),
	BINDER::template GetFn<true,false,false,false,false,false,false,true>(),
	BINDER::template GetFn<false,true,false,false,false,false,false,true>(),
	BINDER::template GetFn<true,true,false,false,false,false,false,true>(),
	BINDER::template GetFn<false,false,true,false,false,false,false,true>(),
	BINDER::template GetFn<true,false,true,false,false,false,false,true>(),
	BINDER::template GetFn<false,true,true,false,false,false,false,true>(),
	BINDER::template GetFn<true,true,true,false,false,false,false,true>(),
	BINDER::template GetFn<false,false,false,true,false,false,false,true>(),
	BINDER::template GetFn<true,false,false,true,false,false,false,true>(),
	BINDER::template GetFn<false,true,false,true,false,false,false,true>(),
	BINDER::template GetFn<true,true,false,true,false,false,false,true>(),
	BINDER::template GetFn<false,false,true,true,false,false,false,true>(),
	BINDER::template GetFn<true,false,true,true,false,false,false,true>(),
	BINDER::template GetFn<false,true,true,true,false,false,false,true>(),
	BINDER::template GetFn<true,true,true,true,false,false,false,true>(),
	BINDER::template GetFn<false,false,false,false,true,false,false,true>(),
	BINDER::template GetFn<true,false,false,false,true,false,false,true>(),
	BINDER::template GetFn<false,true,false,false,true,false,false,true>(),
	BINDER::template GetFn<true,true,false,false,true,false,false,true>(),
	BINDER::template GetFn<false,false,true,false,true,false,false,true>(),
	BINDER::template GetFn<true,false,true,false,true,false,false,true>(),
	BINDER::template GetFn<false,true,true,false,true,false,false,true>(),
	BINDER::template GetFn<true,true,true,false,true,false,false,true>(),
	BINDER::template GetFn<false,false,false,true,true,false,false,true>(),
	BINDER::template GetFn<true,false,false,true,true,false,false,true>(),
	BINDER::template GetFn<false,true,false,true,true,false,false,true>(),
	BINDER::template GetFn<true,true,false,true,true,false,false,true>(),
	BINDER::template GetFn<false,false,true,true,true,false,false,true>(),
	BINDER::template GetFn<true,false,true,true,true,false,false,true>(),
	BINDER::template GetFn<false,true,true,true,true,false,false,true>(),
	BINDER::template GetFn<true,true,true,true,true,false,false,true>(),
	BINDER::template GetFn<false,false,false,false,false,true,false,true>(),
	BINDER::template GetFn<true,false,false,false,false,true,false,true>(),
	BINDER::template GetFn<false,true,false,false,false,true,false,true>(),
	BINDER::template GetFn<true,true,false,false,false,true,false,true>(),
	BINDER::template GetFn<false,false,true,false,false,true,false,true>(),
	BINDER::template GetFn<true,false,true,false,false,true,false,true>(),
	BINDER::template GetFn<false,true,true,false,false,true,false,true>(),
	BINDER::template GetFn<true,true,true,false,false,true,false,true>(),
	BINDER::template GetFn<false,false,false,true,false,true,false,true>(),
	BINDER::template GetFn<true,false,false,true,false,true,false,true>(),
	BINDER::template GetFn<false,true,false,true,false,true,false,true>(),
	BINDER::template GetFn<true,true,false,true,false,true,false,true>(),
	BINDER::template GetFn<false,false,true,true,false,true,false,true>(),
	BINDER::template GetFn<true,false,true,true,false,true,false,true>(),
	BINDER::template GetFn<false,true,true,true,false,true,false,true>(),
	BINDER::template GetFn<true,true,true,true,false,true,false,true>(),
	BINDER::template GetFn<false,false,false,false,true,true,false,true>(),
	BINDER::template GetFn<true,false,false,false,true,true,false,true>(),
	BINDER::template GetFn<false,true,false,false,true,true,false,true>(),
	BINDER::template GetFn<true,true,false,false,true,true,false,true>(),
	BINDER::template GetFn<false,false,true,false,true,true,false,true>(),
	BINDER::template GetFn<true,false,true,false,true,true,false,true>(),
	BINDER::template GetFn<false,true,true,false,true,true,false,true>(),
	BINDER::template GetFn<true,true,true,false,true,true,false,true>(),
	BINDER::template GetFn<false,false,false,true,true,true,false,true>(),
	BINDER::template GetFn<true,false,false,true,true,true,false,true>(),
	BINDER::template GetFn<false,true,false,true,true,true,false,true>(),
	BINDER::template GetFn<true,true,false,true,true,true,false,true>(),
	BINDER::template GetFn<false,false,true,true,true,true,false,true>(),
	BINDER::template GetFn<true,false,true,true,true,true,false,true>(),
	BINDER::template GetFn<false,true,true,true,true,true,false,true>(),
	BINDER::template GetFn<true,true,true,true,true,true,false,true>(),
	BINDER::template GetFn<false,false,false,false,false,false,true,true>(),
	BINDER::template GetFn<true,false,false,false,false,false,true,true>(),
	BINDER::template GetFn<false,true,false,false,false,false,true,true>(),
	BINDER::template GetFn<true,true,false,false,false,false,true,true>(),
	BINDER::template GetFn<false,false,true,false,false,false,true,true>(),
	BINDER::template GetFn<true,false,true,false,false,false,true,true>(),
	BINDER::template GetFn<false,true,true,false,false,false,true,true>(),
	BINDER::template GetFn<true,true,true,false,false,false,true,true>(),
	BINDER::template GetFn<false,false,false,true,false,false,true,true>(),
	BINDER::template GetFn<true,false,false,true,false,false,true,true>(),
	BINDER::template GetFn<false,true,false,true,false,false,true,true>(),
	BINDER::template GetFn<true,true,false,true,false,false,true,true>(),
	BINDER::template GetFn<false,false,true,true,false,false,true,true>(),
	BINDER::template GetFn<true,false,true,true,false,false,true,true>(),
	BINDER::template GetFn<false,true,true,true,false,false,true,true>(),
	BINDER::template GetFn<true,true,true,true,false,false,true,true>(),
	BINDER::template GetFn<false,false,false,false,true,false,true,true>(),
	BINDER::template GetFn<true,false,false,false,true,false,true,true>(),
	BINDER::template GetFn<false,true,false,false,true,false,true,true>(),
	BINDER::template GetFn<true,true,false,false,true,false,true,true>(),
	BINDER::template GetFn<false,false,true,false,true,false,true,true>(),
	BINDER::template GetFn<true,false,true,false,true,false,true,true>(),
	BINDER::template GetFn<false,true,true,false,true,false,true,true>(),
	BINDER::template GetFn<true,true,true,false,true,false,true,true>(),
	BINDER::template GetFn<false,false,false,true,true,false,true,true>(),
	BINDER::template GetFn<true,false,false,true,true,false,true,true>(),
	BINDER::template GetFn<false,true,false,true,true,false,true,true>(),
	BINDER::template GetFn<true,true,false,true,true,false,true,true>(),
	BINDER::template GetFn<false,false,true,true,true,false,true,true>(),
	BINDER::template GetFn<true,false,true,true,true,false,true,true>(),
	BINDER::template GetFn<false,true,true,true,true,false,true,true>(),
	BINDER::template GetFn<true,true,true,true,true,false,true,true>(),
	BINDER::template GetFn<false,false,false,false,false,true,true,true>(),
	BINDER::template GetFn<true,false,false,false,false,true,true,true>(),
	BINDER::template GetFn<false,true,false,false,false,true,true,true>(),
	BINDER::template GetFn<true,true,false,false,false,true,true,true>(),
	BINDER::template GetFn<false,false,true,false,false,true,true,true>(),
	BINDER::template GetFn<true,false,true,false,false,true,true,true>(),
	BINDER::template GetFn<false,true,true,false,false,true,true,true>(),
	BINDER::template GetFn<true,true,true,false,false,true,true,true>(),
	BINDER::template GetFn<false,false,false,true,false,true,true,true>(),
	BINDER::template GetFn<true,false,false,true,false,true,true,true>(),
	BINDER::template GetFn<false,true,false,true,false,true,true,true>(),
	BINDER::template GetFn<true,true,false,true,false,true,true,true>(),
	BINDER::template GetFn<false,false,true,true,false,true,true,true>(),
	BINDER::template GetFn<true,false,true,true,false,true,true,true>(),
	BINDER::template GetFn<false,true,true,true,false,true,true,true>(),
	BINDER::template GetFn<true,true,true,true,false,true,true,true>(),
	BINDER::template GetFn<false,false,false,false,true,true,true,true>(),
	BINDER::template GetFn<true,false,false,false,true,true,true,true>(),
	BINDER::template GetFn<false,true,false,false,true,true,true,true>(),
	BINDER::template GetFn<true,true,false,false,true,true,true,true>(),
	BINDER::template GetFn<false,false,true,false,true,true,true,true>(),
	BINDER::template GetFn<true,false,true,false,true,true,true,true>(),
	BINDER::template GetFn<false,true,true,false,true,true,true,true>(),
	BINDER::template GetFn<true,true,true,false,true,true,true,true>(),
	BINDER::template GetFn<false,false,false,true,true,true,true,true>(),
	BINDER::template GetFn<true,false,false,true,true,true,true,true>(),
	BINDER::template GetFn<false,true,false,true,true,true,true,true>(),
	BINDER::template GetFn<true,true,false,true,true,true,true,true>(),
	BINDER::template GetFn<false,false,true,true,true,true,true,true>(),
	BINDER::template GetFn<true,false,true,true,true,true,true,true>(),
	BINDER::template GetFn<false,true,true,true,true,true,true,true>(),
	BINDER::template GetFn<true,true,true,true,true,true,true,true>(),
};
