# ReflexBuild.cmake
#
# Low-level, target-scoped build operations shared by generated projects and
# the higher-level conveniences in ReflexHelpers.cmake.  This module does not
# locate, download, or link Reflex itself; dependency acquisition is a separate
# concern and link items remain ordinary CMake target/library names.

include_guard(GLOBAL)

# Translate CMake's target-system predicates into the platform model used by
# project.cfg. Call this in the consuming directory before testing these values.
# REFLEX_PLATFORM_NAME is windows, macos, ios, android, linux, or unknown;
# exactly one matching REFLEX_PLATFORM_* value is ON for a recognized platform.
function(reflex_detect_platform)
    set(_platform unknown)
    set(_is_windows OFF)
    set(_is_macos OFF)
    set(_is_ios OFF)
    set(_is_android OFF)
    set(_is_linux OFF)

    if(WIN32)
        set(_platform windows)
        set(_is_windows ON)
    elseif(APPLE AND CMAKE_SYSTEM_NAME STREQUAL "iOS")
        set(_platform ios)
        set(_is_ios ON)
    elseif(APPLE)
        set(_platform macos)
        set(_is_macos ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
        set(_platform android)
        set(_is_android ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(_platform linux)
        set(_is_linux ON)
    endif()

    set(REFLEX_PLATFORM_NAME "${_platform}" PARENT_SCOPE)
    set(REFLEX_PLATFORM_WINDOWS "${_is_windows}" PARENT_SCOPE)
    set(REFLEX_PLATFORM_MACOS "${_is_macos}" PARENT_SCOPE)
    set(REFLEX_PLATFORM_IOS "${_is_ios}" PARENT_SCOPE)
    set(REFLEX_PLATFORM_ANDROID "${_is_android}" PARENT_SCOPE)
    set(REFLEX_PLATFORM_LINUX "${_is_linux}" PARENT_SCOPE)
endfunction()

function(reflex_get_cli output)
    if(DEFINED REFLEX_CLI_EXECUTABLE)
        set(${output} "${REFLEX_CLI_EXECUTABLE}" PARENT_SCOPE)
        return()
    endif()
    if(NOT DEFINED REFLEX_ROOT)
        message(FATAL_ERROR
            "Reflex: REFLEX_ROOT is required to locate the CLI; set REFLEX_CLI_EXECUTABLE explicitly")
    endif()
    if(WIN32)
        set(_cli "${REFLEX_ROOT}/bin/tools/win/reflex.exe")
    elseif(APPLE)
        set(_cli "${REFLEX_ROOT}/bin/tools/macos/reflex")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(_cli "${REFLEX_ROOT}/bin/tools/linux/reflex")
    else()
        message(FATAL_ERROR "Reflex: no CLI location is defined for '${CMAKE_SYSTEM_NAME}'")
    endif()
    set(${output} "${_cli}" PARENT_SCOPE)
endfunction()

function(_reflex_build_require_target target)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "Reflex: '${target}' is not a CMake target")
    endif()
endfunction()

function(_reflex_build_config_expression output config value)
    if(config)
        set(${output} "$<$<CONFIG:${config}>:${value}>" PARENT_SCOPE)
    else()
        set(${output} "${value}" PARENT_SCOPE)
    endif()
endfunction()

function(_reflex_build_apply_target_defaults target)
    _reflex_build_require_target("${target}")
    if(MSVC)
        target_compile_options(${target} PRIVATE /MP)
    endif()
    if(WIN32)
        target_compile_definitions(${target} PRIVATE UNICODE _UNICODE)
    endif()
    if(CMAKE_GENERATOR STREQUAL "Xcode")
        set_target_properties(${target} PROPERTIES
            XCODE_GENERATE_SCHEME ON
            XCODE_SCHEME_ENVIRONMENT "MALLOC_PERMIT_INSANE_REQUESTS=1")
    endif()
endfunction()

function(reflex_add_target target)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "TYPE" "SOURCES")
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "reflex_add_target(${target}): unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT ARG_TYPE)
        message(FATAL_ERROR "reflex_add_target(${target}): TYPE is required")
    endif()

    string(TOUPPER "${ARG_TYPE}" _type)
    if(_type STREQUAL "CONSOLE")
        add_executable(${target} ${ARG_SOURCES})
    elseif(_type STREQUAL "APP")
        if(WIN32)
            add_executable(${target} WIN32 ${ARG_SOURCES})
        elseif(APPLE)
            add_executable(${target} MACOSX_BUNDLE ${ARG_SOURCES})
        else()
            add_executable(${target} ${ARG_SOURCES})
        endif()
    elseif(_type STREQUAL "STATIC_LIBRARY")
        add_library(${target} STATIC ${ARG_SOURCES})
    elseif(_type STREQUAL "DYNAMIC_LIBRARY")
        add_library(${target} SHARED ${ARG_SOURCES})
    elseif(_type STREQUAL "MODULE_LIBRARY")
        add_library(${target} MODULE ${ARG_SOURCES})
    else()
        message(FATAL_ERROR
            "reflex_add_target(${target}): TYPE must be CONSOLE, APP, STATIC_LIBRARY, DYNAMIC_LIBRARY, or MODULE_LIBRARY")
    endif()

    # Match the native emitters' baseline compiler settings.
    _reflex_build_apply_target_defaults(${target})
endfunction()

function(reflex_target_set_cpp_standard target standard)
    _reflex_build_require_target("${target}")
    string(TOUPPER "${standard}" _standard)
    if(_standard STREQUAL "CXX17")
        target_compile_features(${target} PRIVATE cxx_std_17)
    elseif(_standard STREQUAL "CXX20")
        target_compile_features(${target} PRIVATE cxx_std_20)
        if(MSVC)
            target_compile_options(${target} PRIVATE /Zc:preprocessor)
        endif()
    else()
        message(FATAL_ERROR "Reflex: invalid C++ standard '${standard}'")
    endif()
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS NO)
endfunction()

function(reflex_target_enable_string_pooling target)
    _reflex_build_require_target("${target}")
    if(MSVC)
        target_compile_options(${target} PRIVATE /GF)
    endif()
endfunction()

function(reflex_target_set_warning_level target level)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "" "CONFIG" "")
    _reflex_build_require_target("${target}")
    string(TOUPPER "${level}" _level)

    if(MSVC)
        if(_level STREQUAL "NONE")
            set(_options /W0)
        elseif(_level STREQUAL "RELAXED")
            set(_options /W2)
        elseif(_level STREQUAL "STANDARD")
            set(_options /W3)
        elseif(_level STREQUAL "PEDANTIC")
            set(_options /W4)
        else()
            message(FATAL_ERROR "Reflex: invalid warning level '${level}'")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        if(_level STREQUAL "NONE")
            set(_options -w)
        elseif(_level STREQUAL "RELAXED")
            set(_options -Wall -Wno-unused-parameter)
        elseif(_level STREQUAL "STANDARD")
            set(_options -Wall -Wextra -Wno-unused-parameter
                -Wno-missing-field-initializers -Wno-char-subscripts -Wno-missing-braces)
        elseif(_level STREQUAL "PEDANTIC")
            set(_options -Wall -Wextra -Wpedantic)
        else()
            message(FATAL_ERROR "Reflex: invalid warning level '${level}'")
        endif()
    else()
        message(FATAL_ERROR
            "Reflex: warning level '${level}' is unsupported by '${CMAKE_CXX_COMPILER_ID}'")
    endif()

    foreach(_option IN LISTS _options)
        _reflex_build_config_expression(_configured "${ARG_CONFIG}" "${_option}")
        target_compile_options(${target} PRIVATE "${_configured}")
    endforeach()
endfunction()

function(reflex_target_set_rtti target enabled)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "" "CONFIG" "")
    _reflex_build_require_target("${target}")
    if(MSVC)
        if(enabled)
            set(_option /GR)
        else()
            set(_option /GR-)
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        if(enabled)
            set(_option -frtti)
        else()
            set(_option -fno-rtti)
        endif()
    else()
        message(FATAL_ERROR "Reflex: RTTI is unsupported by '${CMAKE_CXX_COMPILER_ID}'")
    endif()
    _reflex_build_config_expression(_configured "${ARG_CONFIG}" "${_option}")
    target_compile_options(${target} PRIVATE "${_configured}")
endfunction()

function(reflex_target_set_floating_point target mode)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "" "CONFIG" "")
    _reflex_build_require_target("${target}")
    string(TOUPPER "${mode}" _mode)
    if(_mode STREQUAL "DEFAULT")
        return()
    endif()

    if(MSVC)
        if(_mode STREQUAL "PRECISE")
            set(_options /fp:precise)
        elseif(_mode STREQUAL "FAST")
            set(_options /fp:fast)
        elseif(_mode STREQUAL "STRICT")
            set(_options /fp:strict)
        else()
            message(FATAL_ERROR "Reflex: invalid floating-point mode '${mode}'")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        if(_mode STREQUAL "PRECISE")
            return()
        elseif(_mode STREQUAL "FAST")
            set(_options -ffast-math)
        elseif(_mode STREQUAL "STRICT")
            set(_options -ffp-model=strict)
        else()
            message(FATAL_ERROR "Reflex: invalid floating-point mode '${mode}'")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        if(_mode STREQUAL "PRECISE")
            return()
        elseif(_mode STREQUAL "FAST")
            set(_options -ffast-math)
        elseif(_mode STREQUAL "STRICT")
            set(_options -frounding-math -fsignaling-nans)
        else()
            message(FATAL_ERROR "Reflex: invalid floating-point mode '${mode}'")
        endif()
    else()
        message(FATAL_ERROR "Reflex: floating-point mode '${mode}' is unsupported by '${CMAKE_CXX_COMPILER_ID}'")
    endif()
    foreach(_option IN LISTS _options)
        _reflex_build_config_expression(_configured "${ARG_CONFIG}" "${_option}")
        target_compile_options(${target} PRIVATE "${_configured}")
    endforeach()
endfunction()

function(reflex_target_set_runtime_library target mode)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "" "" "DEBUG_CONFIGS")
    _reflex_build_require_target("${target}")
    string(TOUPPER "${mode}" _mode)
    if(MSVC)
        if(ARG_DEBUG_CONFIGS)
            list(JOIN ARG_DEBUG_CONFIGS "," _debug_configs)
            set(_debug_suffix "$<$<CONFIG:${_debug_configs}>:Debug>")
        else()
            set(_debug_suffix "$<$<CONFIG:Debug>:Debug>")
        endif()
        if(_mode STREQUAL "STATIC")
            set_property(TARGET ${target} PROPERTY MSVC_RUNTIME_LIBRARY
                "MultiThreaded${_debug_suffix}")
        elseif(_mode STREQUAL "DYNAMIC")
            set_property(TARGET ${target} PROPERTY MSVC_RUNTIME_LIBRARY
                "MultiThreaded${_debug_suffix}DLL")
        else()
            message(FATAL_ERROR "Reflex: invalid runtime library '${mode}'")
        endif()
    elseif(_mode STREQUAL "STATIC" AND CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND NOT APPLE)
        target_link_options(${target} PRIVATE -static-libgcc -static-libstdc++)
    elseif(NOT (_mode STREQUAL "STATIC" OR _mode STREQUAL "DYNAMIC"))
        message(FATAL_ERROR "Reflex: invalid runtime library '${mode}'")
    endif()
endfunction()

function(reflex_target_set_output_directory target directory)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "" "CONFIG" "")
    _reflex_build_require_target("${target}")
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR
            "reflex_target_set_output_directory(${target}): unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT directory)
        message(FATAL_ERROR "reflex_target_set_output_directory(${target}): directory is required")
    endif()
    if(NOT IS_ABSOLUTE "${directory}")
        set(directory "${CMAKE_CURRENT_SOURCE_DIR}/${directory}")
    endif()

    set(_suffix "")
    if(ARG_CONFIG)
        string(TOUPPER "${ARG_CONFIG}" _config)
        set(_suffix "_${_config}")
    endif()
    foreach(_kind RUNTIME LIBRARY ARCHIVE)
        set_property(TARGET ${target} PROPERTY "${_kind}_OUTPUT_DIRECTORY${_suffix}" "${directory}")
    endforeach()
endfunction()

function(reflex_target_set_apple_deployment_target target version)
    _reflex_build_require_target("${target}")
    if(NOT version)
        message(FATAL_ERROR
            "reflex_target_set_apple_deployment_target(${target}): version is required")
    endif()
    if(NOT APPLE)
        return()
    endif()

    if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        set(_xcode_attribute XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET)
        if(CMAKE_OSX_SYSROOT MATCHES "simulator")
            set(_option "-mios-simulator-version-min=${version}")
        else()
            set(_option "-miphoneos-version-min=${version}")
        endif()
    else()
        set(_xcode_attribute XCODE_ATTRIBUTE_MACOSX_DEPLOYMENT_TARGET)
        set(_option "-mmacosx-version-min=${version}")
    endif()

    if(CMAKE_GENERATOR STREQUAL "Xcode")
        set_property(TARGET ${target} PROPERTY "${_xcode_attribute}" "${version}")
    else()
        target_compile_options(${target} PRIVATE "${_option}")
        target_link_options(${target} PRIVATE "${_option}")
    endif()
endfunction()

function(reflex_target_set_objc_arc target enabled)
    _reflex_build_require_target("${target}")
    if(NOT APPLE)
        return()
    endif()

    if(enabled)
        set(_xcode_value YES)
        set(_option -fobjc-arc)
    else()
        set(_xcode_value NO)
        set(_option -fno-objc-arc)
    endif()
    if(CMAKE_GENERATOR STREQUAL "Xcode")
        set_property(TARGET ${target} PROPERTY XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC "${_xcode_value}")
    else()
        target_compile_options(${target} PRIVATE
            "$<$<COMPILE_LANGUAGE:OBJC,OBJCXX>:${_option}>")
    endif()
endfunction()

function(reflex_target_set_macos_exported_symbols target symbols)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "" "CONFIG" "")
    _reflex_build_require_target("${target}")
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR
            "reflex_target_set_macos_exported_symbols(${target}): unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT symbols)
        message(FATAL_ERROR "reflex_target_set_macos_exported_symbols(${target}): symbols file is required")
    endif()
    if(NOT APPLE OR CMAKE_SYSTEM_NAME STREQUAL "iOS")
        return()
    endif()

    _reflex_build_config_expression(_configured "${ARG_CONFIG}"
        "LINKER:-exported_symbols_list,${symbols}")
    target_link_options(${target} PRIVATE "${_configured}")
    set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${symbols}")
endfunction()

function(reflex_target_set_optimization target level)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "" "CONFIG" "")
    _reflex_build_require_target("${target}")
    string(TOUPPER "${level}" _level)

    if(MSVC)
        if(_level STREQUAL "NONE")
            set(_options /Od)
        elseif(_level STREQUAL "SIZE")
            set(_options /O1)
        elseif(_level STREQUAL "SPEED")
            set(_options /O2)
        elseif(_level STREQUAL "FULL")
            set(_options /Ox)
        else()
            message(FATAL_ERROR "Reflex: invalid optimization level '${level}'")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        if(_level STREQUAL "NONE")
            set(_options -O0)
        elseif(_level STREQUAL "SIZE")
            set(_options -Os)
        elseif(_level STREQUAL "SPEED")
            set(_options -O2)
        elseif(_level STREQUAL "FULL")
            set(_options -O3)
        else()
            message(FATAL_ERROR "Reflex: invalid optimization level '${level}'")
        endif()
    else()
        message(FATAL_ERROR "Reflex: optimization is unsupported by '${CMAKE_CXX_COMPILER_ID}'")
    endif()

    foreach(_option IN LISTS _options)
        _reflex_build_config_expression(_configured "${ARG_CONFIG}" "${_option}")
        target_compile_options(${target} PRIVATE "${_configured}")
    endforeach()
endfunction()

function(reflex_target_set_debug_information target enabled)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "" "CONFIG" "")
    _reflex_build_require_target("${target}")
    if(NOT enabled)
        return()
    endif()
    if(MSVC)
        set(_compile /Zi)
        set(_link /DEBUG)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        set(_compile -g)
    else()
        message(FATAL_ERROR "Reflex: debug information is unsupported by '${CMAKE_CXX_COMPILER_ID}'")
    endif()
    _reflex_build_config_expression(_configured "${ARG_CONFIG}" "${_compile}")
    target_compile_options(${target} PRIVATE "${_configured}")
    if(_link)
        _reflex_build_config_expression(_configured "${ARG_CONFIG}" "${_link}")
        target_link_options(${target} PRIVATE "${_configured}")
    endif()
endfunction()

function(reflex_target_set_dead_strip target enabled)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "" "CONFIG" "")
    _reflex_build_require_target("${target}")
    if(NOT enabled)
        return()
    endif()
    if(MSVC)
        set(_compile /Gy)
        set(_link /OPT:REF /OPT:ICF)
    elseif(APPLE)
        set(_compile -ffunction-sections -fdata-sections)
        set(_link -Wl,-dead_strip)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        set(_compile -ffunction-sections -fdata-sections)
        set(_link -Wl,--gc-sections)
    else()
        message(FATAL_ERROR "Reflex: dead stripping is unsupported by '${CMAKE_CXX_COMPILER_ID}'")
    endif()
    foreach(_option IN LISTS _compile)
        _reflex_build_config_expression(_configured "${ARG_CONFIG}" "${_option}")
        target_compile_options(${target} PRIVATE "${_configured}")
    endforeach()
    foreach(_option IN LISTS _link)
        _reflex_build_config_expression(_configured "${ARG_CONFIG}" "${_option}")
        target_link_options(${target} PRIVATE "${_configured}")
    endforeach()
endfunction()

function(reflex_target_add_build_action target)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "ALWAYS_RUN" "PHASE;NAME;WORKING_DIRECTORY;CONFIG" "COMMAND;INPUTS;OUTPUTS")
    _reflex_build_require_target("${target}")
    if(NOT ARG_COMMAND)
        message(FATAL_ERROR "reflex_target_add_build_action(${target}): COMMAND is required")
    endif()
    if(NOT ARG_PHASE MATCHES "^(PRE_BUILD|POST_BUILD)$")
        message(FATAL_ERROR "reflex_target_add_build_action(${target}): PHASE must be PRE_BUILD or POST_BUILD")
    endif()
    if(NOT ARG_NAME)
        set(ARG_NAME "Reflex build action")
    endif()

    if(ARG_CONFIG)
        set(_condition "$<CONFIG:${ARG_CONFIG}>")
        foreach(_kind COMMAND INPUTS OUTPUTS)
            set(_configured)
            foreach(_value IN LISTS ARG_${_kind})
                list(APPEND _configured "$<${_condition}:${_value}>")
            endforeach()
            set(ARG_${_kind} ${_configured})
        endforeach()
    endif()

    # PRE_BUILD is a genuine pre-compilation event only for Visual Studio, but
    # its target signature cannot express dependencies.
    if(ARG_PHASE STREQUAL "PRE_BUILD"
            AND CMAKE_GENERATOR MATCHES "^Visual Studio"
            AND NOT ARG_INPUTS
            AND (ARG_ALWAYS_RUN OR NOT ARG_OUTPUTS))
        add_custom_command(TARGET ${target} PRE_BUILD
            COMMAND ${ARG_COMMAND}
            WORKING_DIRECTORY "${ARG_WORKING_DIRECTORY}"
            BYPRODUCTS ${ARG_OUTPUTS}
            COMMENT "${ARG_NAME}"
            VERBATIM COMMAND_EXPAND_LISTS)
        return()
    endif()

    if(ARG_PHASE STREQUAL "POST_BUILD")
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${ARG_COMMAND}
            WORKING_DIRECTORY "${ARG_WORKING_DIRECTORY}"
            BYPRODUCTS ${ARG_OUTPUTS}
            COMMENT "${ARG_NAME}"
            VERBATIM COMMAND_EXPAND_LISTS)
        return()
    endif()

    get_property(_index GLOBAL PROPERTY REFLEX_BUILD_ACTION_INDEX)
    if(NOT _index)
        set(_index 0)
    endif()
    math(EXPR _next "${_index} + 1")
    set_property(GLOBAL PROPERTY REFLEX_BUILD_ACTION_INDEX "${_next}")
    set(_action_target "${target}__reflex_pre_${_next}")

    if(ARG_OUTPUTS AND NOT ARG_ALWAYS_RUN)
        add_custom_command(OUTPUT ${ARG_OUTPUTS}
            COMMAND ${ARG_COMMAND}
            WORKING_DIRECTORY "${ARG_WORKING_DIRECTORY}"
            DEPENDS ${ARG_INPUTS}
            COMMENT "${ARG_NAME}"
            VERBATIM COMMAND_EXPAND_LISTS)
        add_custom_target(${_action_target} DEPENDS ${ARG_OUTPUTS})
    else()
        add_custom_target(${_action_target}
            COMMAND ${ARG_COMMAND}
            WORKING_DIRECTORY "${ARG_WORKING_DIRECTORY}"
            DEPENDS ${ARG_INPUTS}
            COMMENT "${ARG_NAME}"
            VERBATIM COMMAND_EXPAND_LISTS)
    endif()
    add_dependencies(${target} ${_action_target})
endfunction()
